Feature/sdk 2396/sdk 2779 extends rg with addition data
spryker-sdk/upgrader pull request #206
Opened 2023-09-13 06:37 UTC by vol4onok

https://spryker.atlassian.net/browse/SDK-2396
https://spryker.atlassian.net/browse/SDK-2779

2023-09-13 07:35 UTC, DmytroKlymanSpryker approved these changes

2023-09-13 08:33 UTC, sergeyspryker requested changes

2023-09-13 08:33 UTC, sergeyspryker commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +            if ($integrationGuide && strlen($integrationGuide) > static::INTEGRATION_GUIDE_LENGTH) {
use mb_strlen in case utf-8 symbols

2023-09-13 08:33 UTC, sergeyspryker commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +                $integrationGuide = substr($integrationGuide, 0, static::INTEGRATION_GUIDE_LENGTH);
mb_substr

2023-09-13 08:33 UTC, sergeyspryker commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +                fn (ReleaseGroupDto $appliedReleaseGroup) => $appliedReleaseGroup->getIntegrationGuide()
return type for `fn`

2023-09-13 08:51 UTC, sergeyspryker approved these changes

2023-09-13 14:21 UTC, DmytroKlymanSpryker approved these changes

2023-09-14 07:19 UTC, VladislavStrelchenko approved these changes

2023-09-15 09:15 UTC, DmytroKlymanSpryker approved these changes

2023-09-15 09:15 UTC, merged