Featere/sdk 4698 show skipped modules
spryker-sdk/upgrader pull request #225
Opened 2023-10-11 05:01 UTC by VladislavStrelchenko

Ticket: https://spryker.atlassian.net/browse/SDK-4698

2023-10-11 09:08 UTC, sergeyspryker requested changes

2023-10-11 09:08 UTC, sergeyspryker commented on src/Upgrade/Application/Dto/ReleaseGroupFilterResponseDto.php
> +    public function __construct(ReleaseGroupDto $releaseGroupDto, ?ModuleDtoCollection $filteredModuleCollection = null)
$proposedModuleCollection

2023-10-11 09:08 UTC, VladislavStrelchenko commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +            var_dump($isEmpty);
++

2023-10-11 09:10 UTC, VladislavStrelchenko commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +        foreach ($filterResponseList as $filterResponse) {
++

2023-10-11 09:18 UTC, VladislavStrelchenko commented on src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
> +
++

2023-10-11 09:22 UTC, VladislavStrelchenko commented on src/Upgrade/Application/Dto/ReleaseGroupFilterResponseDto.php
> +    public function __construct(ReleaseGroupDto $releaseGroupDto, ?ModuleDtoCollection $filteredModuleCollection = null)
++

2023-10-12 11:35 UTC, DmytroKlymanSpryker approved these changes

2023-10-12 12:08 UTC, merged